"use strict";

exports.__esModule = true;
exports["default"] = void 0;
var icons = [{
  name: 'icon-camera',
  font: 'e900'
}, {
  name: 'icon-cheveron-down',
  font: 'e901'
}, {
  name: 'icon-cheveron-left',
  font: 'e902'
}, {
  name: 'icon-cheveron-right',
  font: 'e903'
}, {
  name: 'icon-cheveron-up',
  font: 'e904'
}, {
  name: 'icon-close',
  font: 'e905'
}, {
  name: 'icon-down-arrow',
  font: 'e906'
}, {
  name: 'icon-facebook',
  font: 'e907'
}, {
  name: 'icon-globe',
  font: 'e908'
}, {
  name: 'icon-google',
  font: 'e90a'
}, {
  name: 'icon-google-plus',
  font: 'e90b'
}, {
  name: 'icon-google-plus3',
  font: 'e90c'
}, {
  name: 'icon-hamburger',
  font: 'e90d'
}, {
  name: 'icon-headphones',
  font: 'e90e'
}, {
  name: 'icon-heart',
  font: 'e90f'
}, {
  name: 'icon-home',
  font: 'e910'
}, {
  name: 'icon-httpslock',
  font: 'e911'
}, {
  name: 'icon-ic-box-calendar-white',
  font: 'e912'
}, {
  name: 'icon-ic-box-clock-timer-white',
  font: 'e913'
}, {
  name: 'icon-ic-browser-chrome',
  font: 'e914'
}, {
  name: 'icon-ic-browser-opera',
  font: 'e915'
}, {
  name: 'icon-ic-browser-safari',
  font: 'e916'
}, {
  name: 'icon-ic-cause-white',
  font: 'e917'
}, {
  name: 'icon-ic-charities-benefited',
  font: 'e918'
}, {
  name: 'icon-ic-comment',
  font: 'e919'
}, {
  name: 'icon-ic-crowdfunding',
  font: 'e91a'
}, {
  name: 'icon-ic-doc',
  font: 'e91b'
}, {
  name: 'icon-ic-donations',
  font: 'e91c'
}, {
  name: 'icon-ic-edit-request',
  font: 'e91d'
}, {
  name: 'icon-ic-employees-involved',
  font: 'e91e'
}, {
  name: 'icon-ic-facebook',
  font: 'e91f'
}, {
  name: 'icon-ic-feed',
  font: 'e920'
}, {
  name: 'icon-ic-file',
  font: 'e921'
}, {
  name: 'icon-ic-file-upload',
  font: 'e922'
}, {
  name: 'icon-ic-go-back',
  font: 'e923'
}, {
  name: 'icon-ic-goods',
  font: 'e924'
}, {
  name: 'icon-ic-hourglass-ended',
  font: 'e925'
}, {
  name: 'icon-ic-hours',
  font: 'e926'
}, {
  name: 'icon-ic-instagram',
  font: 'e928'
}, {
  name: 'icon-ic-location',
  font: 'e929'
}, {
  name: 'icon-ic-menu-auctions',
  font: 'e92a'
}, {
  name: 'icon-ic-menu-donations',
  font: 'e92b'
}, {
  name: 'icon-ic-menu-manage-store',
  font: 'e92c'
}, {
  name: 'icon-ic-menu-payments',
  font: 'e92d'
}, {
  name: 'icon-ic-menu-requests-gray',
  font: 'e92e'
}, {
  name: 'icon-ic-menu-store',
  font: 'e92f'
}, {
  name: 'icon-ic-notification-bell',
  font: 'e930'
}, {
  name: 'icon-icon-delete',
  font: 'e931'
}, {
  name: 'icon-icon-faq',
  font: 'e932'
}, {
  name: 'icon-icon-feed',
  font: 'e933'
}, {
  name: 'icon-icon-giftcards',
  font: 'e934'
}, {
  name: 'icon-icon-growdfunding',
  font: 'e935'
}, {
  name: 'icon-icon-ic-volunteering',
  font: 'e936'
}, {
  name: 'icon-icon-manage-employees',
  font: 'e937'
}, {
  name: 'icon-icon-payments',
  font: 'e938'
}, {
  name: 'icon-icons-manage-employees',
  font: 'e939'
}, {
  name: 'icon-icon-statistics',
  font: 'e93a'
}, {
  name: 'icon-icon-volunteering',
  font: 'e93b'
}, {
  name: 'icon-ic-ppt',
  font: 'e93c'
}, {
  name: 'icon-ic-request-goods-gray',
  font: 'e93d'
}, {
  name: 'icon-ic-settings',
  font: 'e93e'
}, {
  name: 'icon-ic-status-comments',
  font: 'e93f'
}, {
  name: 'icon-ic-status-volunteers',
  font: 'e940'
}, {
  name: 'icon-ic-survey',
  font: 'e941'
}, {
  name: 'icon-ic-txt',
  font: 'e942'
}, {
  name: 'icon-ic-up',
  font: 'e943'
}, {
  name: 'icon-ic-verification-phone-code',
  font: 'e944'
}, {
  name: 'icon-ic-view-request',
  font: 'e945'
}, {
  name: 'icon-ic-volunteering',
  font: 'e946'
}, {
  name: 'icon-ic-website',
  font: 'e947'
}, {
  name: 'icon-ic-xls',
  font: 'e948'
}, {
  name: 'icon-import-employees',
  font: 'e949'
}, {
  name: 'icon-instagram',
  font: 'e94a'
}, {
  name: 'icon-left-arrow',
  font: 'e94b'
}, {
  name: 'icon-linkedin2',
  font: 'e94c'
}, {
  name: 'icon-mail4',
  font: 'e94d'
}, {
  name: 'icon-menu-mobile',
  font: 'e94e'
}, {
  name: 'icon-pdf',
  font: 'e94f'
}, {
  name: 'icon-pinterest',
  font: 'e950'
}, {
  name: 'icon-right',
  font: 'e951'
}, {
  name: 'icon-right-arrow',
  font: 'e952'
}, {
  name: 'icon-star-full',
  font: 'e953'
}, {
  name: 'icon-telegram',
  font: 'e954'
}, {
  name: 'icon-twitter',
  font: 'e955'
}, {
  name: 'icon-up-arrow',
  font: 'e956'
}, {
  name: 'icon-vimeo',
  font: 'e957'
}, {
  name: 'icon-youtube',
  font: 'e958'
}, {
  name: 'icon-image',
  font: 'e95a'
}, {
  name: 'icon-projects',
  font: 'e959'
}];
var _default = icons;
exports["default"] = _default;
module.exports = exports.default;