import React from 'react';
import ProjectAddForm from './ProjectAddForm';
import variables from '../../assets/sass/_export.module.scss';
import configProjectOld from '../../../__mocks__/configProjectOld';
import configProjectNew from '../../../__mocks__/configProjectNew';

export default {
  title: 'Components/Projects/ProjectAddForm',
  component: ProjectAddForm,
  argTypes: {
    color: {
      control: {
        type: 'object',
      },
    },
  },
};

const Template = args => <ProjectAddForm {...args} />;

export const Default = Template.bind({});
export const Edit = Template.bind({});
export const Old = Template.bind({});
Default.parameters = {
  jest: ['ProjectAddForm.test.js'],
};
Default.args = {
  uploadImagesLabel: 'Images',
  hideDropZone: false,
  color: {
    primaryColor: variables['theme-colors-primary'],
  },
  errors: {},
  lang: 'pt',
  categories: [
    {
      id: 69,
      whitelabel_id: 5,
      name: 'Corporate behaviour 123',
      summary:
        'Solutions that improve transparency, honesty, and fairness at a corporate level amongst the workforce and consumers',
      status: 1,
      image: 'projects/categories/afa78f54-5c1f-4845-b2e3-c30e407a76e1.jpg',
      updated_at: '2021-12-09 10:48:45',
      created_at: '2021-12-09 10:48:13',
    },
    {
      id: 61,
      whitelabel_id: 5,
      name: 'Energia',
      summary:
        'Soluções que visam reduzir os requisitos de energia através de processos mais eficientes em energia',
      status: 1,
      image: '',
      updated_at: '2021-12-09 10:48:13',
      created_at: '2021-12-06 17:22:27',
    },
    {
      id: 66,
      whitelabel_id: 5,
      name: 'Materiais',
      summary:
        'Soluções que visam minimizar o uso de matérias-primas (recursos naturais, produtos químicos manufaturados e materiais necessários para a fabricação), materiais de embalagem e conteúdo de produto reciclado',
      status: 1,
      image: '',
      updated_at: '2021-12-09 10:48:13',
      created_at: '2021-12-07 14:35:12',
    },
  ],
  ods: [
    {
      id: 1,
      ods_id: 1,
      tag_name: 'ods-1',
      status: true,
      updated_at: '2020-02-05 17:26:34',
      created_at: '2020-02-05 17:26:27',
      name: '1-ods-1',
    },
    {
      id: 2,
      ods_id: 2,
      tag_name: 'ods-2',
      status: true,
      updated_at: '2020-02-05 17:26:41',
      created_at: '2020-02-05 17:26:41',
      name: '2-ods-2',
    },
    {
      id: 3,
      ods_id: 3,
      tag_name: 'ods-3',
      status: true,
      updated_at: '2020-02-05 17:26:46',
      created_at: '2020-02-05 17:26:46',
      name: '3-ods-3',
    },
    {
      id: 4,
      ods_id: 4,
      tag_name: 'ods-4',
      status: true,
      updated_at: '2020-02-05 17:38:12',
      created_at: '2020-02-05 17:38:12',
      name: '4-ods-4',
    },
    {
      id: 5,
      ods_id: 5,
      tag_name: 'ods-5',
      status: true,
      updated_at: '2020-02-05 17:38:18',
      created_at: '2020-02-05 17:38:18',
      name: '5-ods-5',
    },
    {
      id: 6,
      ods_id: 6,
      tag_name: 'ods-6',
      status: true,
      updated_at: '2020-02-05 18:03:39',
      created_at: '2020-02-05 18:03:39',
      name: '6-ods-6',
    },
    {
      id: 7,
      ods_id: 7,
      tag_name: 'ods-7',
      status: true,
      updated_at: '2020-02-05 18:03:44',
      created_at: '2020-02-05 18:03:44',
      name: '7-ods-7',
    },
    {
      id: 8,
      ods_id: 8,
      tag_name: 'ods-8',
      status: true,
      updated_at: '2020-02-05 18:03:49',
      created_at: '2020-02-05 18:03:49',
      name: '8-ods-8',
    },
    {
      id: 9,
      ods_id: 9,
      tag_name: 'ods-9',
      status: true,
      updated_at: '2020-02-05 18:03:53',
      created_at: '2020-02-05 18:03:53',
      name: '9-ods-9',
    },
    {
      id: 10,
      ods_id: 10,
      tag_name: 'ods-10',
      status: true,
      updated_at: '2020-02-05 18:03:58',
      created_at: '2020-02-05 18:03:58',
      name: '10-ods-10',
    },
    {
      id: 11,
      ods_id: 11,
      tag_name: 'ods-11',
      status: true,
      updated_at: '2020-02-05 18:04:04',
      created_at: '2020-02-05 18:04:04',
      name: '11-ods-11',
    },
    {
      id: 12,
      ods_id: 12,
      tag_name: 'ods-12',
      status: true,
      updated_at: '2020-02-05 18:04:08',
      created_at: '2020-02-05 18:04:08',
      name: '12-ods-12',
    },
    {
      id: 13,
      ods_id: 13,
      tag_name: 'ods-13',
      status: true,
      updated_at: '2020-02-05 18:04:13',
      created_at: '2020-02-05 18:04:13',
      name: '13-ods-13',
    },
    {
      id: 14,
      ods_id: 14,
      tag_name: 'ods-14',
      status: true,
      updated_at: '2020-02-05 18:04:19',
      created_at: '2020-02-05 18:04:19',
      name: '14-ods-14',
    },
    {
      id: 15,
      ods_id: 15,
      tag_name: 'ods-15',
      status: true,
      updated_at: '2020-02-05 18:04:26',
      created_at: '2020-02-05 18:04:26',
      name: '15-ods-15',
    },
    {
      id: 16,
      ods_id: 16,
      tag_name: 'ods-16',
      status: true,
      updated_at: '2020-02-05 18:04:31',
      created_at: '2020-02-05 18:04:31',
      name: '16-ods-16',
    },
    {
      id: 17,
      ods_id: 17,
      tag_name: 'ods-17',
      status: true,
      updated_at: '2020-02-05 18:04:37',
      created_at: '2020-02-05 18:04:37',
      name: '17-ods-17',
    },
  ],
  images: [],
  form: JSON.parse(configProjectNew.form),
  dragAndDropMessage:
    'Arraste e solte alguns ficheiros aqui ou clique para selecionar os ficheiros',
  onChangeCheckbox: () => {},
  onChangeRadiobox: () => {},
};

Edit.args = {
  uploadImagesLabel: 'Images',
  hideDropZone: false,
  color: {
    primaryColor: variables['theme-colors-primary'],
  },
  errors: {},
  lang: 'pt',
  categories: [
    {
      id: 69,
      whitelabel_id: 5,
      name: 'Corporate behaviour 123',
      summary:
        'Solutions that improve transparency, honesty, and fairness at a corporate level amongst the workforce and consumers',
      status: 1,
      image: 'projects/categories/afa78f54-5c1f-4845-b2e3-c30e407a76e1.jpg',
      updated_at: '2021-12-09 10:48:45',
      created_at: '2021-12-09 10:48:13',
    },
    {
      id: 61,
      whitelabel_id: 5,
      name: 'Energia',
      summary:
        'Soluções que visam reduzir os requisitos de energia através de processos mais eficientes em energia',
      status: 1,
      image: '',
      updated_at: '2021-12-09 10:48:13',
      created_at: '2021-12-06 17:22:27',
    },
    {
      id: 66,
      whitelabel_id: 5,
      name: 'Materiais',
      summary:
        'Soluções que visam minimizar o uso de matérias-primas (recursos naturais, produtos químicos manufaturados e materiais necessários para a fabricação), materiais de embalagem e conteúdo de produto reciclado',
      status: 1,
      image: '',
      updated_at: '2021-12-09 10:48:13',
      created_at: '2021-12-07 14:35:12',
    },
  ],
  ods: [
    {
      id: 1,
      checked: true,
      ods_id: 1,
      tag_name: 'ods-1',
      status: true,
      updated_at: '2020-02-05 17:26:34',
      created_at: '2020-02-05 17:26:27',
      name: '1-ods-1',
    },
    {
      id: 2,
      ods_id: 2,
      tag_name: 'ods-2',
      status: true,
      updated_at: '2020-02-05 17:26:41',
      created_at: '2020-02-05 17:26:41',
      name: '2-ods-2',
    },
    {
      id: 3,
      checked: true,
      ods_id: 3,
      tag_name: 'ods-3',
      status: true,
      updated_at: '2020-02-05 17:26:46',
      created_at: '2020-02-05 17:26:46',
      name: '3-ods-3',
    },
    {
      id: 4,
      ods_id: 4,
      tag_name: 'ods-4',
      status: true,
      updated_at: '2020-02-05 17:38:12',
      created_at: '2020-02-05 17:38:12',
      name: '4-ods-4',
    },
    {
      id: 5,
      ods_id: 5,
      tag_name: 'ods-5',
      status: true,
      updated_at: '2020-02-05 17:38:18',
      created_at: '2020-02-05 17:38:18',
      name: '5-ods-5',
    },
    {
      id: 6,
      checked: true,
      ods_id: 6,
      tag_name: 'ods-6',
      status: true,
      updated_at: '2020-02-05 18:03:39',
      created_at: '2020-02-05 18:03:39',
      name: '6-ods-6',
    },
    {
      id: 7,
      ods_id: 7,
      tag_name: 'ods-7',
      status: true,
      updated_at: '2020-02-05 18:03:44',
      created_at: '2020-02-05 18:03:44',
      name: '7-ods-7',
    },
    {
      id: 8,
      ods_id: 8,
      tag_name: 'ods-8',
      status: true,
      updated_at: '2020-02-05 18:03:49',
      created_at: '2020-02-05 18:03:49',
      name: '8-ods-8',
    },
    {
      id: 9,
      ods_id: 9,
      tag_name: 'ods-9',
      status: true,
      updated_at: '2020-02-05 18:03:53',
      created_at: '2020-02-05 18:03:53',
      name: '9-ods-9',
    },
    {
      id: 10,
      ods_id: 10,
      tag_name: 'ods-10',
      status: true,
      updated_at: '2020-02-05 18:03:58',
      created_at: '2020-02-05 18:03:58',
      name: '10-ods-10',
    },
    {
      id: 11,
      ods_id: 11,
      tag_name: 'ods-11',
      status: true,
      updated_at: '2020-02-05 18:04:04',
      created_at: '2020-02-05 18:04:04',
      name: '11-ods-11',
    },
    {
      id: 12,
      ods_id: 12,
      tag_name: 'ods-12',
      status: true,
      updated_at: '2020-02-05 18:04:08',
      created_at: '2020-02-05 18:04:08',
      name: '12-ods-12',
    },
    {
      id: 13,
      ods_id: 13,
      tag_name: 'ods-13',
      status: true,
      updated_at: '2020-02-05 18:04:13',
      created_at: '2020-02-05 18:04:13',
      name: '13-ods-13',
    },
    {
      id: 14,
      ods_id: 14,
      tag_name: 'ods-14',
      status: true,
      updated_at: '2020-02-05 18:04:19',
      created_at: '2020-02-05 18:04:19',
      name: '14-ods-14',
    },
    {
      id: 15,
      ods_id: 15,
      tag_name: 'ods-15',
      status: true,
      updated_at: '2020-02-05 18:04:26',
      created_at: '2020-02-05 18:04:26',
      name: '15-ods-15',
    },
    {
      id: 16,
      ods_id: 16,
      tag_name: 'ods-16',
      status: true,
      updated_at: '2020-02-05 18:04:31',
      created_at: '2020-02-05 18:04:31',
      name: '16-ods-16',
    },
    {
      id: 17,
      ods_id: 17,
      tag_name: 'ods-17',
      status: true,
      updated_at: '2020-02-05 18:04:37',
      created_at: '2020-02-05 18:04:37',
      name: '17-ods-17',
    },
  ],
  newImages: [
    {
      id: 261,
      project_id: 114,
      streamImage: 'amazons3',
      image: 'whitelabel/5/projects/905937cd-d059-4284-9c34-a05595e9c989.jpg',
      image_type: 'jpg',
      image_size: 744830,
      default: 1,
      position: 1,
      updated_at: '2021-12-14 16:35:04',
      created_at: '2021-12-14 16:34:57',
    },
  ],
  images: [261],
  form: {
    title: 'Título ',
    description: 'Descrição ',
    video: 'video',
    images: [],
    categories: 61,
    sdg: {
      required: false,
      include: true,
      data: [],
      preferred: [1],
    },
    customQuestions: [
      {
        id: 0,
        type: 'section',
        form: {
          privacy: 'public',
          required: false,
          title: 'title',
          description: {
            blocks: [
              {
                key: '13g9d',
                text: 'description',
                type: 'unstyled',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
            ],
            entityMap: {},
          },
        },
      },
      {
        id: 1,
        type: 'shortAnswer',
        form: {
          privacy: 'public',
          required: false,
          question: 'A solução é Inovadora?',
          description:
            'A solução do seu projeto é inovadora se resolver o problema de uma forma mais eficaz',
        },
        reply: 'A solução é Inovadora',
      },
      {
        id: 2,
        type: 'longAnswer',
        form: {
          privacy: 'public',
          required: true,
          question: 'Qual o problema social/ambiental que pretende a resolver? ',
          description:
            'Justifique porque o problema que está a resolver é 1) Importante (afecta um grande número de pessoas ou um pequeno número de forma muito profunda), é 2) Negligenciado (não está a ser resolvido por outras soluções de forma eficaz), e 3) Gera externalidades (a existência deste problema gera consequências negativas).',
        },
        reply: 'Qual o problema social/ambiental que pretende a resolver?  ',
      },
      {
        id: 3,
        type: 'multiChoice',
        form: {
          privacy: 'private',
          required: true,
          question: "How's the weather today?",
          description: 'Check your weather app',
          options: [
            {
              id: 0,
              value: 'Sunny',
            },
            {
              id: 1,
              value: 'Rainy',
            },
            {
              id: 2,
              value: 'Cloudy',
            },
          ],
        },
        reply: 2,
      },
      {
        id: 4,
        type: 'checkboxes',
        form: {
          privacy: 'public',
          required: true,
          question: 'Escolha as opções que mais lhe agradam',
          description: '',
          answersAllowed: 'range',
          exact: null,
          rangeMin: 2,
          rangeMax: 3,
          options: [
            {
              id: 0,
              value: 'Cinema',
            },
            {
              id: 1,
              value: 'Literatura',
            },
            {
              id: 2,
              value: 'Praia',
            },
            {
              id: 3,
              value: 'Montanha',
            },
          ],
        },
        reply: [0, 1, 3],
      },
      {
        id: 5,
        type: 'section',
        form: {
          privacy: 'public',
          title: 'A sua solução é escalável e replicável? ',
          description: {
            blocks: [
              {
                key: '58kdm',
                text: 'Justifique porque o problema que está a resolver é',
                type: 'unstyled',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
              {
                key: '60hb2',
                text: 'Importante (afecta um grande número de pessoas ou um pequeno número de forma muito profunda)',
                type: 'ordered-list-item',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
              {
                key: 'erm40',
                text: 'Negligenciado (não está a ser resolvido por outras soluções de forma eficaz)',
                type: 'ordered-list-item',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
              {
                key: 'dfnmb',
                text: 'Gera externalidades (a existência deste problema gera consequências negativas)',
                type: 'ordered-list-item',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
            ],
            entityMap: {},
          },
        },
      },
      {
        id: 6,
        type: 'longAnswer',
        form: {
          privacy: 'public',
          required: true,
          question: 'Qual o modelo de governança da sua Iniciativa? ',
          description:
            'Exemplo: Segue um modelo partilhado entre o sector publico e o sector privado.',
        },
        reply: 'Qual o modelo de governança da sua Iniciativa?',
      },
      {
        id: 7,
        type: 'shortAnswer',
        form: {
          privacy: 'private',
          required: true,
          question: 'O seu email',
          description: 'Este campo apenas será visivel para os administradores do programa',
        },
        reply: 'O seu email ',
      },
    ],
  },
  dragAndDropMessage:
    'Arraste e solte alguns ficheiros aqui ou clique para selecionar os ficheiros',
  onChangeCheckbox: () => {},
  onChangeRadiobox: () => {},
  onChange: () => {},
};

Old.args = {
  uploadImagesLabel: 'Upload images (Min. 500px X 470px and a maximum of 5MB)',
  uploadImagesLabelTitle: 'Images',
  hideDropZone: false,
  color: {
    primaryColor: variables['theme-colors-primary'],
  },
  errors: {},
  lang: 'pt',
  categories: [
    {
      id: 1,
      name: 'Categoria 1',
    },
    {
      id: 2,
      name: 'Categoria 2',
    },
  ],
  ods: [
    {
      id: 1,
      ods_id: 1,
      tag_name: 'ods-1',
      status: true,
      updated_at: '2020-02-05 17:26:34',
      created_at: '2020-02-05 17:26:27',
      name: '1-ods-1',
    },
    {
      id: 2,
      ods_id: 2,
      tag_name: 'ods-2',
      status: true,
      updated_at: '2020-02-05 17:26:34',
      created_at: '2020-02-05 17:26:27',
      name: '2-ods-2',
      checked: true,
    },
  ],
  images: [
    {
      created_at: '2020-07-29 11:41:36',
      default: 1,
      id: 152,
      image: 'whitelabel/5/projects/93f4af44-4755-4993-be56-2fbf283ccb27.jpg',
      image_size: 33970,
      image_type: 'jpg',
      position: 1,
      project_id: 54,
      streamImage: 'amazons3',
      updated_at: '2020-07-29 11:42:59',
    },
    {
      created_at: '2020-07-29 11:41:39',
      default: 0,
      id: 153,
      image: 'whitelabel/5/projects/255ff6ea-adc1-4773-b115-8b67bc62cfe0.jpg',
      image_size: 316018,
      image_type: 'jpg',
      position: 3,
      project_id: 54,
      streamImage: 'amazons3',
      updated_at: '2020-07-29 11:42:59',
    },
  ],
  form: JSON.parse(configProjectOld.form),
  dragAndDropMessage:
    'Arraste e solte alguns ficheiros aqui ou clique para selecionar os ficheiros',
  onChangeCheckbox: () => {},
  onChangeRadiobox: () => {},
};
