const configProjectNew = {
  id: 40,
  whitelabel_id: 5,
  archived_by: null,
  title: 'Lorem ipsum dolor sit amet, cons',
  intro:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a sollicitudin lectus. Cras libero urna, semper non ipsum at, egestas ornare purus. Sed diam justo, accumsan sed pharetra sed, mattis sed purus. Aliquam vel mauris id urna blandit condimentum. Etiam scelerisque cursus faucibus. Integer quis fringilla lacus. Donec at congue turpis. Donec pulvinar dolor ut mauris pretium posuere. Vest',
  program_format:
    'Fusce malesuada pharetra libero. Mauris varius eros sed enim bibendum, quis vulputate tortor pharetra. Suspendisse ut semper dui. Phasellus id commodo libero. Vivamus congue, elit eget lobortis dignissim, mi erat semper turpis, id tempor arcu tellus et dolor. Suspendisse et justo augue. Sed vulputate lacus vehicula turpis iaculis congue euismod non odio. Aliquam et lacus at arcu fringilla auctor n',
  who_should_apply:
    'Aliquam massa tortor, imperdiet vitae elit sit amet, dictum aliquam ipsum. In sit amet ante turpis. Pellentesque auctor velit sit amet est dictum, eu ornare libero accumsan. Vestibulum sem sem, consectetur vel placerat ut, suscipit sed lorem. Phasellus posuere elit sit amet dolor tincidunt hendrerit. Ut ac tempus augue, dapibus lobortis orci. Donec rutrum tincidunt fermentum. In laoreet dui imperd',
  remote: false,
  location: 'Rua de Caires 256, Braga, Portugal',
  location_address: '{"address":"Rua de Caires 256 \\n4700-211 Braga\\nPortugal"}',
  latitude: 41.547134,
  longitude: -8.4335018,
  summary:
    '{"paginator":[{"active":true,"status":"not-done","title":"Detalhes gerais"},{"active":false,"status":"not-done","title":"Localização e Duração"},{"active":false,"status":"not-done","title":"Categorias"},{"active":false,"status":"not-done","title":"Competências e interesses"},{"active":false,"status":"not-done","title":"Formulário de inscrição"}]}',
  form: JSON.stringify({
    title: '',
    description: '',
    video: '',
    images: [],
    categories: {
      required: true,
      data: [],
      show: true,
    },
    sdg: {
      required: false,
      include: true,
      data: [],
      preferred: [1],
    },
    customQuestions: [
      {
        id: 0,
        type: 'section',
        form: {
          privacy: 'public',
          required: false,
          title: 'title',
          description: {
            blocks: [
              {
                key: '13g9d',
                text: 'description',
                type: 'unstyled',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
            ],
            entityMap: {},
          },
        },
      },
      {
        id: 1,
        type: 'shortAnswer',
        form: {
          privacy: 'public',
          required: false,
          question: 'A solução é Inovadora?',
          description:
            'A solução do seu projeto é inovadora se resolver o problema de uma forma mais eficaz',
        },
      },
      {
        id: 2,
        type: 'longAnswer',
        form: {
          privacy: 'public',
          required: true,
          question: 'Qual o problema social/ambiental que pretende a resolver? ',
          description:
            'Justifique porque o problema que está a resolver é 1) Importante (afecta um grande número de pessoas ou um pequeno número de forma muito profunda), é 2) Negligenciado (não está a ser resolvido por outras soluções de forma eficaz), e 3) Gera externalidades (a existência deste problema gera consequências negativas).',
        },
      },
      {
        id: 3,
        type: 'multiChoice',
        form: {
          privacy: 'private',
          required: true,
          question: "How's the weather today?",
          description: 'Check your weather app',
          options: [
            {
              id: 0,
              value: 'Sunny',
            },
            {
              id: 1,
              value: 'Rainy',
            },
            {
              id: 2,
              value: 'Cloudy',
            },
          ],
        },
      },
      {
        id: 4,
        type: 'checkboxes',
        form: {
          privacy: 'public',
          required: true,
          question: 'Escolha as opções que mais lhe agradam',
          description: '',
          answersAllowed: 'range',
          exact: null,
          rangeMin: 2,
          rangeMax: 3,
          options: [
            {
              id: 0,
              value: 'Cinema',
            },
            {
              id: 1,
              value: 'Literatura',
            },
            {
              id: 2,
              value: 'Praia',
            },
            {
              id: 3,
              value: 'Montanha',
            },
          ],
        },
      },
      {
        id: 5,
        type: 'section',
        form: {
          privacy: 'public',
          title: 'A sua solução é escalável e replicável? ',
          description: {
            blocks: [
              {
                key: '58kdm',
                text: 'Justifique porque o problema que está a resolver é',
                type: 'unstyled',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
              {
                key: '60hb2',
                text: 'Importante (afecta um grande número de pessoas ou um pequeno número de forma muito profunda)',
                type: 'ordered-list-item',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
              {
                key: 'erm40',
                text: 'Negligenciado (não está a ser resolvido por outras soluções de forma eficaz)',
                type: 'ordered-list-item',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
              {
                key: 'dfnmb',
                text: 'Gera externalidades (a existência deste problema gera consequências negativas)',
                type: 'ordered-list-item',
                depth: 0,
                inlineStyleRanges: [],
                entityRanges: [],
                data: {},
              },
            ],
            entityMap: {},
          },
        },
      },
      {
        id: 6,
        type: 'longAnswer',
        form: {
          privacy: 'public',
          required: true,
          question: 'Qual o modelo de governança da sua Iniciativa? ',
          description:
            'Exemplo: Segue um modelo partilhado entre o sector publico e o sector privado.',
        },
      },
      {
        id: 7,
        type: 'shortAnswer',
        form: {
          privacy: 'private',
          required: true,
          question: 'O seu email',
          description: 'Este campo apenas será visivel para os administradores do programa',
        },
      },
    ],
  }),
  additional_texts:
    '{"paginator":[{"active":false,"status":"done","title":"Detalhes gerais"},{"active":false,"status":"done","title":"Localização e Duração"},{"active":false,"status":"done","title":"Categorias"},{"active":false,"status":"done","title":"Competências e interesses"},{"active":true,"status":"done","title":"Formulário de inscrição"}]}',
  status: true,
  timezone: 'UTC',
  start_at: '2021-12-13 20:00:00',
  closed_at: '2021-12-15 20:00:00',
  ended_at: '2021-12-31 20:00:00',
  archived_at: null,
  archived_motivation: null,
  updated_at: '2021-12-10 10:33:28',
  created_at: '2021-12-06 11:31:16',
  running_projects: 0,
  skills: [
    {
      id: 1,
      type: 'hard',
      name_pt: 'Artes e Artesanato',
      name_en: 'Arts & Crafts',
      name_br: ' Artes e Artesanato',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:01',
      created_at: '2021-11-16 16:41:40',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 1,
      },
    },
    {
      id: 3,
      type: 'hard',
      name_pt: 'Cozinha e Limpeza',
      name_en: 'Cleaning & Cooking',
      name_br: 'Cozinha e Limpeza',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 10:59:59',
      created_at: '2021-11-16 17:36:41',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 3,
      },
    },
    {
      id: 4,
      type: 'hard',
      name_pt: 'Computadores e TI',
      name_en: ' Computers & IT',
      name_br: 'Computadores e TI',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 10:59:59',
      created_at: '2021-11-16 17:36:55',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 4,
      },
    },
    {
      id: 12,
      type: 'hard',
      name_pt: 'Gerenciamento de projetos',
      name_en: 'Project management',
      name_br: 'Gerenciamento de projetos',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:00',
      created_at: '2021-11-22 11:00:00',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 12,
      },
    },
    {
      id: 13,
      type: 'hard',
      name_pt: 'Sustentabilidade e Ambiente',
      name_en: 'Sustainability & Environment',
      name_br: 'Sustentabilidade e Ambiente',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:00',
      created_at: '2021-11-22 11:00:00',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 13,
      },
    },
    {
      id: 15,
      type: 'soft',
      name_pt: 'Comunicação',
      name_en: 'Communication',
      name_br: 'Comunicação',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:00',
      created_at: '2021-11-22 11:00:00',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 15,
      },
    },
    {
      id: 17,
      type: 'soft',
      name_pt: 'Pensamento crítico',
      name_en: 'Critical thinking',
      name_br: 'Pensamento crítico',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:00',
      created_at: '2021-11-22 11:00:00',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 17,
      },
    },
    {
      id: 18,
      type: 'soft',
      name_pt: 'Atendimento ao cliente',
      name_en: 'Customer service',
      name_br: 'Atendimento ao cliente',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:00',
      created_at: '2021-11-22 11:00:00',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 18,
      },
    },
    {
      id: 19,
      type: 'soft',
      name_pt: 'Empatia e Escuta',
      name_en: 'Empathy & Listening',
      name_br: 'Empatia e Escuta',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:01',
      created_at: '2021-11-22 11:00:01',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 19,
      },
    },
    {
      id: 21,
      type: 'soft',
      name_pt: 'Organização e Planejamento',
      name_en: 'Organization & Planning',
      name_br: 'Organização e Planejamento',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:01',
      created_at: '2021-11-22 11:00:01',
      deleted_at: null,
      pivot: {
        project_config_id: 40,
        skill_id: 21,
      },
    },
  ],
  interests: [
    {
      id: 4,
      name_pt: 'Fé e Religião',
      name_en: 'Faith & Religion',
      name_br: 'Fé e Religião',
      description_pt: null,
      description_en: null,
      description_br: null,
      deleted_at: null,
      updated_at: '2021-11-22 11:07:03',
      created_at: '2021-11-17 17:00:20',
      pivot: {
        project_config_id: 40,
        interest_id: 4,
      },
      image: null,
    },
  ],
  images: [
    {
      id: 60,
      project_config_id: 40,
      streamImage: 'amazons3',
      image: 'whitelabel/5/project-config/8c7c59dc-3d55-416b-9e49-cd23c917dd9f.jpg',
      image_type: 'jpg',
      image_size: '134648',
      updated_at: '2021-12-09 11:00:15',
      created_at: '2021-12-09 11:00:15',
    },
  ],
};

export default configProjectNew;
