const institution = {
  id: 30,
  owner_id: 5,
  owner_name: null,
  owner_email: null,
  owner_phone: null,
  category_id: 1,
  email: 'vieira.setima+helpo@gmail.com',
  code: null,
  name: 'Helpo',
  charity_number: null,
  sigla: 'helpo',
  early_adopter: 0,
  summary:
    'Agimos para a implementação da educação e amadurecimento do desenvolvimento humano da população, como base para a aceitação da diferença, consciencialização e mobilização da sociedade civil para a resolução dos problemas sociais globais.',
  description:
    '<br><span style="font-weight: bold;">Visão, Missão e Valores</span><br><br><br>A Helpo é uma Organização Não Governamental para o Desenvolvimento, sem fins lucrativos, de Direito Português, nascida a 26 de Novembro de 2004. É uma Organização laica e apolítica que leva a cabo programas de apoio continuados, projectos de assistência, ajuda humanitária, desenvolvimento comunitário, educação para o desenvolvimento e desenvolvimento humano em múltiplos países do hemisfério Norte e Sul do Mundo e que se serve, para a concretização das suas actividades, da colaboração dos seus parceiros, associados, funcionários, padrinhos e voluntários cuja motivação se coadune com a Missão, Visão e Valores da Organização.<br><br><br><span style="font-weight: bold;">Visão</span><br><br>A Visão da Organização reside:<br><br><ul><li>Na melhoria da condição da população e grupos desfavorecidos do Sul do Mundo, na senda do desenvolvimento económico, social e humano partindo da perspectiva comunitária para um âmbito sempre mais global e abrangente;</li></ul><ul><li>E numa consciencialização efectiva do Norte do Mundo acerca destas problemáticas desenhando um caminho comum que leve à sua resolução.</li></ul><br><br><span style="font-weight: bold;">Missão</span><br><br>A Missão que pretende tornar tangível a nossa Visão é a realização de projectos educativos, formativos e de geração de rendimento que permitam a capacitação dos indivíduos e grupos das populações locais partindo da convicção de que o conhecimento e a utilização de ferramentas adequadas possibilitam o desfrutar de uma condição mais elevada e de uma vida mais digna. Acreditamos e agimos para a implementação da educação para o desenvolvimento e amadurecimento do desenvolvimento humano da população, como base para a aceitação da diferença, consciencialização e mobilização da sociedade civil no sentido de participar na resolução dos problemas sociais globais.<br>Valores<br><br>Os vectores de intervenção, que em parte decorrem da aplicação do programa de Apadrinhamento de Crianças à Distância (ACD), centram-se na assistência alimentar; educativa; sanitária; empowerment; geração de rendimento próprio; educação para o desenvolvimento, desenvolvimento humano e ajuda humanitária e de emergência.',
  fb_fan_page: null,
  twitter_account: null,
  youtube: null,
  instagram: null,
  linkedin: null,
  giftaid: 0,
  status: 1,
  validated: 1,
  accept_volunteer: 1,
  accept_donations: 1,
  paypal_email: 'donativos@esolidar.com',
  bic: null,
  iban: 'PT50 0010 0000 3483 3480 0032 8',
  nib: null,
  nif: null,
  ukbanksortcode: null,
  ukaccountnumber: null,
  ukaccountholder: null,
  streamImage: 'amazons3',
  image:
    'https://esolidar-proto-uploads.s3.eu-west-1.amazonaws.com/institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3.png',
  cover_image:
    'https://s3.eu-west-1.amazonaws.com/esolidar-proto-uploads/institutions/cover/fdc46ea6-fea3-446c-87e4-178610260c04.jpeg',
  thumb: 0,
  country: 208,
  language: 2,
  currency: {
    id: 2,
    name: 'U. S. Dollar',
    small: 'USD',
    value: '1',
    symbol: '$',
    status: true,
    lastUpdate: '2014-02-03 15:50:54',
  },
  link: 'www.helpo.pt',
  phone: '+351 21 153 76 87',
  fax: '',
  address:
    'Associação Helpo,\r\nRua Catarina Eufémia, 167A, Fontainhas,\r\n2750-318 Cascais, Portugal',
  location: 'Cascais, Portugal',
  latitude: '38.6970565',
  longitude: '-9.422294500000021',
  notes: null,
  thanking_message: null,
  featured: 0,
  giftcard: 0,
  match_donation: 0,
  bank_transfer: null,
  lastUpdate: '2019-10-30 12:41:19',
  dateAdded: '2014-01-30 16:28:45',
  thumbs: {
    detail:
      'https://cdn.testesolidar.com/institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3-DETAIL.png',
    thumb:
      'https://cdn.testesolidar.com/institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3-THUMB.png',
  },
  s3_image_key: 'institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3.png',
  s3_cover_key: 'institutions/cover/fdc46ea6-fea3-446c-87e4-178610260c04.jpeg',
  user_id: 1124,
};

export default institution;
