const institution = {
  about: {
    br: 'Mauris faucibus nulla lacus, in accumsan metus lacinia vitae. Ut vulputate, nunc vitae pellentesque efficitur, purus purus egestas nisi, sed fermentum enim arcu sed nisi. Vestibulum arcu tortor, imperdiet a accumsan sit amet, lacinia pharetra ipsum. Nulla mauris orci, dictum nec risus at, pellentesque malesuada justo. Vivamus euismod tempus justo, vel lobortis sapien. Integer id tortor lacinia, accumsan ipsum id, maximus est. Pellentesque malesuada mi et arcu vestibulum, vel gravida enim vestibulum. Phasellus pulvinar odio ut nunc eleifend, ac dictum mi tristique. In quis dui mattis, congue nulla hendrerit, malesuada nunc. Nulla congue euismod lacus, eget tempor elit efficitur a. Sed non leo elementum, mollis arcu sit amet, sagittis tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc molestie mollis erat ut finibus. Morbi vel est at diam finibus dignissim in ac nibh. Quisque tincidunt facilisis vulputate. Etiam elementum arcu sed sapien sagittis, a rutrum ligula ultrices.\n\nDonec consequat egestas tellus, non convallis orci varius a. Morbi hendrerit dui ante, varius sodales nisl bibendum non. Nunc consectetur, lorem vitae tincidunt feugiat, dolor orci porta augue, in lacinia diam orci quis eros. Praesent semper massa sit amet varius convallis. Phasellus ac bibendum odio. Ut quam massa, molestie ac felis et, dignissim ullamcorper neque. Proin nibh dolor, lacinia in venenatis et, ullamcorper ut magna. Fusce posuere, leo gravida finibus ornare, quam libero porttitor arcu, ac auctor mi neque a purus. Morbi lorem libero, fermentum at sapien ac, tristique posuere urna. Curabitur condimentum in nulla hendrerit dictum. Vestibulum tincidunt eu ligula vitae auctor.',
    en: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac malesuada quam, et scelerisque ipsum. Nullam aliquam ac orci ac maximus. Sed ac diam elit. Etiam quis euismod enim. Nullam iaculis ante a sem consequat malesuada. Maecenas hendrerit lectus quis tempor congue. Nullam at nibh turpis. Nulla facilisis porta laoreet. Morbi tempor mattis massa. Proin nec mi a libero sodales ullamcorper. Donec vitae finibus sem. Aliquam nibh est, consequat et nisi a, molestie placerat nulla.\n\nIn feugiat justo luctus posuere pulvinar. Sed laoreet efficitur sem, vitae vestibulum lectus mollis id. In pharetra felis id molestie luctus. Fusce commodo molestie risus ut condimentum. Maecenas eget turpis bibendum, molestie diam vitae, pellentesque nisi. Nam pulvinar efficitur libero, vitae feugiat ligula vestibulum convallis. Mauris id tellus quis orci venenatis ullamcorper sit amet non leo.\n\nMauris faucibus nulla lacus, in accumsan metus lacinia vitae. Ut vulputate, nunc vitae pellentesque efficitur, purus purus egestas nisi, sed fermentum enim arcu sed nisi. Vestibulum arcu tortor, imperdiet a accumsan sit amet, lacinia pharetra ipsum. Nulla mauris orci, dictum nec risus at, pellentesque malesuada justo. Vivamus euismod tempus justo, vel lobortis sapien. Integer id tortor lacinia, accumsan ipsum id, maximus est. Pellentesque malesuada mi et arcu vestibulum, vel gravida enim vestibulum. Phasellus pulvinar odio ut nunc eleifend, ac dictum mi tristique. In quis dui mattis, congue nulla hendrerit, malesuada nunc. Nulla congue euismod lacus, eget tempor elit efficitur a. Sed non leo elementum, mollis arcu sit amet, sagittis tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc molestie mollis erat ut finibus. Morbi vel est at diam finibus dignissim in ac nibh. Quisque tincidunt facilisis vulputate. Etiam elementum arcu sed sapien sagittis, a rutrum ligula ultrices.',
    pt: 'Donec consequat egestas tellus, non convallis orci varius a. Morbi hendrerit dui ante, varius sodales nisl bibendum non. Nunc consectetur, lorem vitae tincidunt feugiat, dolor orci porta augue, in lacinia diam orci quis eros. Praesent semper massa sit amet varius convallis. Phasellus ac bibendum odio. Ut quam massa, molestie ac felis et, dignissim ullamcorper neque. Proin nibh dolor, lacinia in venenatis et, ullamcorper ut magna. Fusce posuere, leo gravida finibus ornare, quam libero porttitor arcu, ac auctor mi neque a purus. Morbi lorem libero, fermentum at sapien ac, tristique posuere urna. Curabitur condimentum in nulla hendrerit dictum. Vestibulum tincidunt eu ligula vitae auctor.\n\nUt rutrum enim sed leo ullamcorper sagittis. Fusce tincidunt, nisi sit amet lacinia mollis, est velit sollicitudin nisl, in placerat tellus risus eget ligula. Suspendisse ultrices sem imperdiet lacus ultrices lobortis. Morbi nec enim pellentesque, maximus sapien sit amet, condimentum risus. Suspendisse potenti. Donec velit nunc, vulputate et ante non, ornare accumsan nulla. Ut tempor, leo eget maximus tempus, ipsum ex rutrum mi, in laoreet velit velit eu orci. Quisque vel mauris varius, fermentum augue et, tempor arcu. Vivamus rhoncus justo justo, vel accumsan augue tincidunt eu. Nunc non ante et dolor convallis rutrum.',
  },
  short_bio: {
    br: 'Mauris faucibus nulla lacus, in accumsan metus lacinia vitae. Ut vulputate, nunc vitae pellentesque efficitur, purus purus egestas nisi',
    en: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac malesuada quam, et scelerisque ipsum. Nullam aliquam ac orci ac maximus.',
    pt: 'Donec consequat egestas tellus, non convallis orci varius a. Morbi hendrerit dui ante, varius sodales nisl bibendum non. Nunc consectetur',
  },
  id: 30,
  owner_id: 5,
  owner_name: null,
  owner_email: null,
  owner_phone: null,
  category_id: 1,
  email: 'vieira.setima+helpo@gmail.com',
  code: null,
  name: 'Helpo',
  charity_number: null,
  sigla: 'helpo',
  early_adopter: 0,
  summary:
    'Agimos para a implementação da educação e amadurecimento do desenvolvimento humano da população, como base para a aceitação da diferença, consciencialização e mobilização da sociedade civil para a resolução dos problemas sociais globais.',
  description:
    '<br><span style="font-weight: bold;">Visão, Missão e Valores</span><br><br><br>A Helpo é uma Organização Não Governamental para o Desenvolvimento, sem fins lucrativos, de Direito Português, nascida a 26 de Novembro de 2004. É uma Organização laica e apolítica que leva a cabo programas de apoio continuados, projectos de assistência, ajuda humanitária, desenvolvimento comunitário, educação para o desenvolvimento e desenvolvimento humano em múltiplos países do hemisfério Norte e Sul do Mundo e que se serve, para a concretização das suas actividades, da colaboração dos seus parceiros, associados, funcionários, padrinhos e voluntários cuja motivação se coadune com a Missão, Visão e Valores da Organização.<br><br><br><span style="font-weight: bold;">Visão</span><br><br>A Visão da Organização reside:<br><br><ul><li>Na melhoria da condição da população e grupos desfavorecidos do Sul do Mundo, na senda do desenvolvimento económico, social e humano partindo da perspectiva comunitária para um âmbito sempre mais global e abrangente;</li></ul><ul><li>E numa consciencialização efectiva do Norte do Mundo acerca destas problemáticas desenhando um caminho comum que leve à sua resolução.</li></ul><br><br><span style="font-weight: bold;">Missão</span><br><br>A Missão que pretende tornar tangível a nossa Visão é a realização de projectos educativos, formativos e de geração de rendimento que permitam a capacitação dos indivíduos e grupos das populações locais partindo da convicção de que o conhecimento e a utilização de ferramentas adequadas possibilitam o desfrutar de uma condição mais elevada e de uma vida mais digna. Acreditamos e agimos para a implementação da educação para o desenvolvimento e amadurecimento do desenvolvimento humano da população, como base para a aceitação da diferença, consciencialização e mobilização da sociedade civil no sentido de participar na resolução dos problemas sociais globais.<br>Valores<br><br>Os vectores de intervenção, que em parte decorrem da aplicação do programa de Apadrinhamento de Crianças à Distância (ACD), centram-se na assistência alimentar; educativa; sanitária; empowerment; geração de rendimento próprio; educação para o desenvolvimento, desenvolvimento humano e ajuda humanitária e de emergência.',
  fb_fan_page: null,
  twitter_account: null,
  youtube: null,
  instagram: null,
  linkedin: null,
  giftaid: 0,
  status: 1,
  validated: 1,
  accept_volunteer: 1,
  accept_donations: 1,
  paypal_email: 'donativos@esolidar.com',
  bic: null,
  iban: 'PT50 0010 0000 3483 3480 0032 8',
  nib: null,
  nif: null,
  ukbanksortcode: null,
  ukaccountnumber: null,
  ukaccountholder: null,
  streamImage: 'amazons3',
  image:
    'https://esolidar-proto-uploads.s3.eu-west-1.amazonaws.com/institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3.png',
  cover_image:
    'https://s3.eu-west-1.amazonaws.com/esolidar-proto-uploads/institutions/cover/fdc46ea6-fea3-446c-87e4-178610260c04.jpeg',
  thumb: 0,
  country: 208,
  language: 2,
  currency: {
    id: 2,
    name: 'U. S. Dollar',
    small: 'USD',
    value: '1',
    symbol: '$',
    status: true,
    lastUpdate: '2014-02-03 15:50:54',
  },
  link: 'www.helpo.pt',
  phone: '+351 21 153 76 87',
  fax: '',
  address:
    'Associação Helpo,\r\nRua Catarina Eufémia, 167A, Fontainhas,\r\n2750-318 Cascais, Portugal',
  location: 'Cascais, Portugal',
  latitude: '38.6970565',
  longitude: '-9.422294500000021',
  notes: null,
  thanking_message: null,
  featured: 0,
  giftcard: 0,
  match_donation: 0,
  bank_transfer: null,
  lastUpdate: '2019-10-30 12:41:19',
  dateAdded: '2014-01-30 16:28:45',
  thumbs: {
    detail:
      'https://cdn.testesolidar.com/institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3-DETAIL.png',
    thumb:
      'https://cdn.testesolidar.com/institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3-THUMB.png',
  },
  s3_image_key: 'institutions/5db984ee-51b4-43c3-b363-23eaac1f17c3.png',
  s3_cover_key: 'institutions/cover/fdc46ea6-fea3-446c-87e4-178610260c04.jpeg',
  user_id: 1124,
};

export default institution;
