const program = {
  id: 464,
  title: 'New program',
  intro:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus euismod aliquam vestibulum. Proin turpis felis, sagittis eu viverra nec, iaculis a felis. Nam non ultricies magna. Vestibulum et hendrerit mauris. Suspendisse tempor ut metus eu scelerisque. Phasellus sit amet diam dolor. Nunc mollis, lectus vel euismod sagittis, sem diam ultrices nunc, lacinia blandit quam quam sed dolor. Etiam pu',
  program_format:
    '{"blocks":[{"key":"98ilt","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus euismod aliquam vestibulum. Proin turpis felis, sagittis eu viverra nec, iaculis a felis. Nam non ultricies magna. Vestibulum et hendrerit mauris. Suspendisse tempor ut metus eu scelerisque. Phasellus sit amet diam dolor. Nunc mollis, lectus vel euismod sagittis, sem diam ultrices nunc, lacinia blandit quam quam sed dolor. Etiam pu","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
  who_should_apply:
    '{"blocks":[{"key":"c8vnd","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus euismod aliquam vestibulum. Proin turpis felis, sagittis eu viverra nec, iaculis a felis. Nam non ultricies magna. Vestibulum et hendrerit mauris. Suspendisse tempor ut metus eu scelerisque. Phasellus sit amet diam dolor. Nunc mollis, lectus vel euismod sagittis, sem diam ultrices nunc, lacinia blandit quam quam sed dolor. Etiam pu","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
  remote: true,
  location: '',
  location_address: null,
  latitude: 0,
  longitude: 0,
  form: '{"title":"","description":"","video":"","images":[],"categories":{"show":true,"required":true},"sdg":{"preferred":[1,3,4],"include":true,"required":true},"customQuestions":[{"type":"section","form":{"privacy":"public","title":"Título da secção","description":{"blocks":[{"key":"sm8a","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus euismod aliquam vestibulum. Proin turpis felis, sagittis eu viverra nec, iaculis a felis. Nam non ultricies magna. Vestibulum et hendrerit mauris. Suspendisse tempor ut metus eu scelerisque. Phasellus sit amet diam dolor. Nunc mollis, lectus vel euismod sagittis, sem diam ultrices nunc, lacinia blandit quam quam sed dolor.","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":18,"length":28,"style":"BOLD"},{"offset":284,"length":15,"style":"STRIKETHROUGH"}],"entityRanges":[],"data":{}},{"key":"8h65e","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"3ken8","text":"Etiam purus urna, sollicitudin ac neque non, bibendum faucibus lorem. Nullam sem tellus, cursus in nulla sit amet, semper mollis massa. Ut euismod faucibus sapien sit amet laoreet. Cras sodales augue sed erat fermentum consectetur id quis mauris. Nulla vehicula odio vel sapien pharetra iaculis. Etiam vehicula placerat dolor, ac lacinia est rhoncus et. Donec ultricies mauris tristique felis ultrices, sit amet condimentum nibh facilisis. In vestibulum nibh neque, sed consequat nisl vehicula vitae. Sed laoreet ligula odio, non eleifend nulla blandit non.","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":53,"style":"BOLD"},{"offset":193,"length":96,"style":"ITALIC"},{"offset":544,"length":13,"style":"UNDERLINE"}],"entityRanges":[],"data":{}}],"entityMap":{}}},"id":0},{"type":"shortAnswer","form":{"privacy":"public","required":false,"question":"Pergunta 1","description":""},"id":1},{"type":"longAnswer","form":{"privacy":"public","required":false,"question":"Pergunta 2","description":"Descrição da pergunta 2"},"id":2},{"type":"fileUploader","form":{"privacy":"public","required":false,"question":"Anexos","description":""},"id":3}]}',
  status: true,
  timezone: 'Europe/Lisbon',
  start_at: '2022-06-06 23:00:00',
  closed_at: '2022-06-30 22:59:59',
  ended_at: '2022-08-01 22:59:59',
  archived_at: null,
  running_projects: 6,
  skills: [
    {
      id: 8,
      type: 'hard',
      name_pt: 'Agricultura e Jardinagem',
      name_en: 'Farming & Gardening',
      name_br: 'Agricultura e Jardinagem',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 10:59:59',
      created_at: '2021-11-22 10:59:59',
      deleted_at: null,
      pivot: {
        project_config_id: 464,
        skill_id: 8,
      },
    },
    {
      id: 12,
      type: 'hard',
      name_pt: 'Gerenciamento de projetos',
      name_en: 'Project management',
      name_br: 'Gerenciamento de projetos',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:00',
      created_at: '2021-11-22 11:00:00',
      deleted_at: null,
      pivot: {
        project_config_id: 464,
        skill_id: 12,
      },
    },
    {
      id: 17,
      type: 'soft',
      name_pt: 'Pensamento crítico',
      name_en: 'Critical thinking',
      name_br: 'Pensamento crítico',
      summary_pt: null,
      summary_en: null,
      summary_br: null,
      updated_at: '2021-11-22 11:00:00',
      created_at: '2021-11-22 11:00:00',
      deleted_at: null,
      pivot: {
        project_config_id: 464,
        skill_id: 17,
      },
    },
  ],
  interests: [
    {
      id: 1,
      name_pt: 'Biodiversidade e Ecossistemas',
      name_en: 'Biodiversity & Ecosystems',
      name_br: 'Biodiversidade e Ecossistemas',
      description_pt: null,
      description_en: null,
      description_br: null,
      deleted_at: null,
      updated_at: '2022-01-24 17:06:01',
      created_at: '2021-12-30 15:29:41',
      pivot: {
        project_config_id: 464,
        interest_id: 1,
      },
      image: {
        id: 3,
        interest_id: 1,
        streamImage: 'amazons3',
        image: 'interests/v2/default/biodiversity-ecosystems.svg',
        action: 'default',
        image_type: 'svg',
        image_size: '533',
        updated_at: '2022-01-24 17:45:23',
        created_at: '2021-12-30 15:29:41',
      },
      default_image: {
        id: 3,
        interest_id: 1,
        streamImage: 'amazons3',
        image: 'interests/v2/default/biodiversity-ecosystems.svg',
        action: 'default',
        image_type: 'svg',
        image_size: '533',
        updated_at: '2022-01-24 17:45:23',
        created_at: '2021-12-30 15:29:41',
      },
      disabled_image: {
        id: 35,
        interest_id: 1,
        streamImage: 'amazons3',
        image: 'interests/v2/disabled/biodiversity-ecosystems.svg',
        action: 'disabled',
        image_type: 'svg',
        image_size: '533',
        updated_at: '2022-01-24 17:45:23',
        created_at: '2021-12-30 15:29:41',
      },
      checked_image: {
        id: 19,
        interest_id: 1,
        streamImage: 'amazons3',
        image: 'interests/v2/active/biodiversity-ecosystems.svg',
        action: 'checked',
        image_type: 'svg',
        image_size: '533',
        updated_at: '2022-01-24 17:45:23',
        created_at: '2021-12-30 15:29:41',
      },
    },
  ],
  images: [
    {
      id: 510,
      project_config_id: 464,
      streamImage: 'amazons3',
      image: 'whitelabel/5/project-config/6da57d5b-d953-4445-bb79-c124e4244fab.jpg',
      image_type: 'jpg',
      image_size: '153099',
      updated_at: '2022-06-07 08:46:24',
      created_at: '2022-06-07 08:45:50',
    },
  ],
};

export default program;
