import company from './company';
import user from './user';
import ods from './ods';

const project = {
  as_company: 1,
  auctions: [],
  category_id: 9,
  cover: null,
  created_at: '2021-07-02 08:57:38',
  crowdfundings: [],
  description: 'DESCRIPTION',
  form: [
    {
      id: 'input-1',
      name: 'Project title',
      type: 'input',
      fixed: true,
      required: true,
      reply: 'PROJECT TITLE',
      position: 0,
      selected: true,
    },
    {
      id: 'input-2',
      name: 'Description',
      type: 'textarea',
      fixed: true,
      required: true,
      reply: 'DESCRIPTION',
      position: 1,
      selected: true,
    },
    {
      id: 'input-3',
      name: 'Categories',
      type: 'dropdown',
      fixed: true,
      required: true,
      reply: '9',
      position: 2,
      selected: true,
    },
    { id: 'input-4', name: 'ODS', type: 'ods', fixed: true, position: 3 },
    { id: 'input-5', name: 'Images', type: 'upload-images', fixed: true, position: 4 },
    { id: 'input-106', name: 'paragraph', type: 'paragraph', isPrivate: false, position: 6 },
    {
      id: 'input-108',
      name: 'long question',
      help: 'help',
      type: 'textarea',
      required: false,
      isPrivate: false,
      reply: 'LONG QUESTION',
      position: 8,
      selected: true,
    },
    {
      id: 'input-109',
      name: 'single question',
      help: 'help',
      type: 'radiobox',
      required: false,
      isPrivate: false,
      options: ['option A', 'option B'],
      reply: 'option A',
      position: 9,
      selected: true,
    },
    {
      id: 'input-110',
      name: 'multiple choice',
      help: 'help',
      type: 'checkbox',
      required: false,
      requiredMin: 1,
      requiredMax: 2,
      isPrivate: false,
      options: ['option A', 'option B'],
      checked: ['option A'],
      position: 10,
      selected: true,
    },
    { id: 'input-105', name: 'title', type: 'title', isPrivate: true, position: 5 },
    {
      id: 'input-107',
      name: 'short question',
      help: 'help',
      type: 'input',
      required: true,
      isPrivate: true,
      reply: 'DESCRIPTION',
      position: 7,
      selected: true,
    },
  ],
  id: 87,
  images: [
    {
      id: 195,
      project_id: 80,
      streamImage: 'amazons3',
      image: 'whitelabel/21/projects/a2ed3a9b-4159-4df4-8974-7c1edf538fd0.jpg',
      image_type: 'jpg',
      image_size: 1745830,
      default: 1,
      position: 1,
      updated_at: '2021-02-01 12:02:02',
      created_at: '2021-02-01 12:02:01',
    },
  ],
  ods: [ods, ods, ods, ods, ods],
  project_category: {
    created_at: '2020-08-06 15:56:39',
    id: 9,
    image: 'projects/categories/29e71c2e-4213-45b0-b388-24d81df1b7a8.jpg',
    name: 'Ambiente',
    name_tag: 'ambiente',
    status: 1,
    summary:
      'A tartaruga-marinha-comum (Caretta caretta) também chamada de tartaruga-amarela, tartaruga-cabeçuda, tartaruga-meio-pente ou tartaruga-mestiça, é uma espécie de tartaruga marinha pertencente à família Cheloniidae. Habita no oceano Atlântico, Pac',
    updated_at: '2021-05-04 13:56:32',
    whitelabel_id: 5,
  },
  review_average: 4,
  status: 'PENDING',
  status_reason: null,
  title: 'PROJECT TITLE',
  updated_at: '2021-07-02 08:57:38',
  user,
  user_id: 9,
  uuid: '52342d72-48c8-49ef-a175-5555ab05978c',
  whitelabel_config: {
    id: 21,
    company_id: 273,
    domain: null,
    subdomain: 'rochacompany.esolidar.local',
    company,
  },
  whitelabel_id: 5,
};

export default project;
