const form = {
  title: '',
  description: '',
  video: '',
  images: [],
  categories: { show: true },
  sdg: { required: false, preferred: [] },
  customQuestions: [
    {
      type: 'section',
      form: {
        privacy: 'private',
        title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description: {
          blocks: [
            {
              key: '11dm0',
              text: 'Nulla nec sapien pharetra, lobortis diam eget, tincidunt neque. Cras vestibulum congue tellus a faucibus. Curabitur vitae convallis nulla. Ut elit est, volutpat mollis vestibulum id, efficitur vel arcu.',
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [],
              entityRanges: [],
              data: {},
            },
            {
              key: '2i4ut',
              text: '',
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [],
              entityRanges: [],
              data: {},
            },
            {
              key: 'fqidp',
              text: 'Suspendisse interdum purus commodo, eleifend enim sit amet, pharetra lorem. Aenean viverra id magna at posuere. Praesent a laoreet purus. Donec vitae felis malesuada, efficitur nibh vel, convallis metus.',
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [],
              entityRanges: [],
              data: {},
            },
            {
              key: '2sh3j',
              text: 'Quisque et urna quis elit mollis congue ut vitae odio.',
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [],
              entityRanges: [],
              data: {},
            },
          ],
          entityMap: {},
        },
      },
      id: 0,
    },
    {
      type: 'shortAnswer',
      form: {
        privacy: 'public',
        required: true,
        question: 'Praesent eget mollis ipsum. Ut in sagittis odio?',
        description:
          'Vestibulum ac luctus ipsum. Suspendisse scelerisque turpis ut urna porttitor aliquet. Praesent eget leo id magna volutpat lobortis quis in nibh.',
      },
      id: 1,
      reply: '',
    },
    {
      type: 'longAnswer',
      form: {
        privacy: 'public',
        required: true,
        question: 'Vestibulum efficitur risus vitae eros ultrices lobortis.',
        description:
          'In in tempor velit. Morbi consectetur, ex sit amet aliquam sollicitudin, orci neque sodales lorem, sed scelerisque nulla ante vel justo.',
      },
      id: 2,
      reply: '',
    },
    {
      type: 'multiChoice',
      form: {
        privacy: 'public',
        required: true,
        question: 'In in tempor velit. Morbi consectetur',
        description: 'Duis ultrices lorem quis quam fringilla luctus.',
        options: [
          { value: 'Duis ultrices lorem quis quam fringilla luctus.', id: 0 },
          { value: 'Vestibulum efficitur risus vitae eros ultrices lobortis.', id: 1 },
          { value: 'Lorem ipsum dolor sit amet', id: 2 },
        ],
      },
      id: 3,
      reply: '2',
    },
    {
      type: 'checkboxes',
      form: {
        privacy: 'private',
        required: true,
        question: 'Cras fermentum semper euismod.',
        description:
          'Cras fermentum semper euismod. Quisque libero ipsum, dapibus quis blandit eget, finibus at erat. Suspendisse sit amet venenatis tellus. Sed tempus, leo vel tempus malesuada',
        answersAllowed: 'range',
        exact: null,
        rangeMin: 3,
        rangeMax: 4,
        options: [
          { value: 'Option 1', id: 0 },
          { value: 'Opção 2', id: 1 },
          { value: 'Opção 3', id: 2 },
          { value: 'Opção 4', id: 3 },
          { value: 'Opção 5', id: 4 },
          { value: 'Opção 6', id: 5 },
        ],
      },
      id: 4,
    },
    {
      type: 'fileUploader',
      form: {
        privacy: 'private',
        required: true,
        question: 'Quisque libero ipsum, dapibus quis blandit eget',
        description:
          'Cras fermentum semper euismod. Quisque libero ipsum, dapibus quis blandit eget, finibus at erat. Suspendisse sit amet venenatis tellus. Sed tempus, leo vel tempus malesuada',
      },
      id: 5,
    },
  ],
};

const projectConfig = {
  request_time: 2978,
  code: 200,
  data: {
    id: 206,
    whitelabel_id: 9,
    archived_by: null,
    title: '´Submit project',
    intro:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s",
    program_format:
      '{"blocks":[{"key":"bpslf","text":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s w","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    who_should_apply:
      '{"blocks":[{"key":"174l1","text":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s w","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    remote: true,
    location: '',
    location_address: '{"floor":"123","info":"text"}',
    latitude: 0,
    longitude: 0,
    summary: '',
    form: JSON.stringify(form),
    draft: '{}',
    additional_texts:
      '{"paginator":{"active":"generalDetails","edited":[],"done":["locationTime","categories","skillsAndInterests","applicationForm","generalDetails"],"published":false}}',
    status: true,
    timezone: 'Europe/Lisbon',
    start_at: '2022-03-03 00:00:00',
    closed_at: '2022-04-04 23:59:59',
    ended_at: '2022-05-05 23:59:59',
    archived_at: null,
    archived_motivation: null,
    updated_at: '2022-03-08 14:32:47',
    created_at: '2022-03-03 14:06:17',
    running_projects: 1,
    skills: [],
    interests: [
      {
        id: 1,
        name_pt: 'Biodiversidade e Ecossistemas',
        name_en: 'Biodiversity & Ecosystems',
        name_br: 'Biodiversidade e Ecossistemas',
        description_pt: null,
        description_en: null,
        description_br: null,
        deleted_at: null,
        updated_at: '2022-01-24 17:06:01',
        created_at: '2021-12-30 15:29:41',
        pivot: {
          project_config_id: 206,
          interest_id: 1,
        },
        image: {
          id: 1,
          interest_id: 1,
          streamImage: 'amazons3',
          image: 'interests/v2/default/biodiversity-ecosystems.svg',
          action: 'default',
          image_type: 'svg',
          image_size: '533',
          updated_at: '2022-01-24 17:45:23',
          created_at: '2021-12-30 15:29:41',
        },
        default_image: {
          id: 1,
          interest_id: 1,
          streamImage: 'amazons3',
          image: 'interests/v2/default/biodiversity-ecosystems.svg',
          action: 'default',
          image_type: 'svg',
          image_size: '533',
          updated_at: '2022-01-24 17:45:23',
          created_at: '2021-12-30 15:29:41',
        },
        disabled_image: {
          id: 36,
          interest_id: 1,
          streamImage: 'amazons3',
          image: 'interests/v2/disabled/biodiversity-ecosystems.svg',
          action: 'disabled',
          image_type: 'svg',
          image_size: '533',
          updated_at: '2022-01-24 17:45:23',
          created_at: '2021-12-30 15:29:41',
        },
        checked_image: {
          id: 20,
          interest_id: 1,
          streamImage: 'amazons3',
          image: 'interests/v2/active/biodiversity-ecosystems.svg',
          action: 'checked',
          image_type: 'svg',
          image_size: '533',
          updated_at: '2022-01-24 17:45:23',
          created_at: '2021-12-30 15:29:41',
        },
      },
    ],
    images: [
      {
        id: 272,
        project_config_id: 206,
        streamImage: 'amazons3',
        image: 'whitelabel/9/project-config/331c26d8-f27d-463f-a9b0-99e39de0986c.jpg',
        image_type: 'jpg',
        image_size: '60666',
        updated_at: '2022-03-08 14:32:47',
        created_at: '2022-03-08 14:32:39',
      },
    ],
  },
};

export default projectConfig;
