import user from './user';
import ods from './ods';

const projectOverview = {
  id: 370,
  whitelabel_id: 5,
  project_config_id: 463,
  category_id: null,
  user_id: 9,
  as_company: 0,
  cover: null,
  video: null,
  title: 'Projeto muito bonito',
  description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit convallis erat in convallis. Sed maximus nibh felis, ac eleifend lorem auctor ac. Curabitur vel porta justo, ultricies consectetur tortor. Donec vestibulum, lectus vitae sollicitudin iaculis, nisi neque rutrum purus, a ultrices neque arcu nec velit. Donec vitae augue nec arcu euismod pharetra pharetra ac nulla. Quisque vulputate, neque quis commodo hendrerit, ipsum dolor rhoncus erat, at pharetra elit dolor gravida risus. Sed vitae aliquet dolor. Sed id tincidunt justo, a vestibulum elit. Integer non dui eleifend, feugiat velit in, dignissim purus. Fusce vitae ullamcorper quam. Maecenas ultricies quis risus et imperdiet. Nunc tempor libero in lorem bibendum congue. Curabitur et ligula ac velit egestas sodales. Nulla lacus odio, tristique ut metus eget, elementum blandit tellus.\r\n\r\nUt pharetra vestibulum venenatis. Donec rutrum ultrices posuere. Nunc sit amet erat odio. Sed nisl diam, malesuada sed ligula vitae, posuere pulvinar massa. Sed libero metus, dictum finibus turpis eget, maximus gravida tellus. Cras sodales condimentum purus a egestas. Fusce consectetur arcu sit amet sem tincidunt laoreet. Integer faucibus in leo vitae tempus. Cras nulla lacus, accumsan eu neque a, dictum aliquam elit. Nulla sem dolor, suscipit quis justo ac, pretium tempor turpis. Curabitur scelerisque interdum mauris et ornare. Donec et tristique magna. Duis bibendum fermentum bibendum. Maecenas sed posuere enim.\r\n\r\nVivamus porttitor vehicula velit nec laoreet. Vestibulum facilisis velit sed sapien cursus finibus. Duis metus lacus, mollis quis tincidunt eu, dignissim quis sapien. Duis ultrices ut tortor in lacinia. Quisque fermentum eget justo quis dapibus. Nullam nec dui posuere orci posuere varius quis vitae tellus. Nulla cursus, dolor vel pellentesque hendrerit, nulla tortor rhoncus nunc, dapibus commodo quam elit in elit. Aliquam nec suscipit turpis, id faucibus justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis tincidunt malesuada accumsan. Sed nec mauris eget elit semper cursus. Sed et justo viverra urna laoreet lobortis id sed erat. Etiam sodales lectus ligula, at consequat justo viverra non. Sed ac ipsum nec nibh consectetur mollis. In hac habitasse platea dictumst. Fusce tincidunt euismod pellentesque.\r\n\r\nIn in diam id dolor tincidunt sollicitudin vel quis tortor. Ut commodo pretium malesuada. Morbi metus nisl, finibus quis euismod nec, ultricies eu tortor. Vivamus purus quam, pharetra consequat turpis non, imperdiet eleifend orci. Ut eu fermentum nisi, at blandit sapien. Cras feugiat venenatis sapien in ullamcorper. Integer condimentum risus feugiat luctus sagittis. Curabitur ut orci posuere nisi dignissim faucibus ut et mauris.',
  form: '[{"type":"section","form":{"privacy":"public","title":"Titulo de secção","description":{"blocks":[{"key":"48e1e","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ac nulla convallis, elementum risus at, ullamcorper arcu. Aenean nulla justo, porta sit amet congue congue, molestie quis nibh. Vestibulum porttitor ex orci, a imperdiet libero blandit quis. Integer purus lectus, sagittis id augue a, mollis gravida arcu. Suspendisse felis elit, sagittis quis ante quis, volutpat rhoncus enim.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}},"id":0,"position":0},{"type":"shortAnswer","form":{"privacy":"public","required":true,"question":"Questão 1","description":""},"id":1,"reply":"Resposta à pergunta 1","position":1},{"type":"longAnswer","form":{"privacy":"public","required":true,"question":"Questão 3","description":""},"id":3,"reply":"Ut pharetra vestibulum venenatis. Donec rutrum ultrices posuere. Nunc sit amet erat odio. Sed nisl diam, malesuada sed ligula vitae, posuere pulvinar massa. Sed libero metus, dictum finibus turpis eget, maximus gravida tellus. Cras sodales condimentum purus a egestas. Fusce consectetur arcu sit amet sem tincidunt laoreet. Integer faucibus in leo vitae tempus. Cras nulla lacus, accumsan eu neque a, dictum aliquam elit. Nulla sem dolor, suscipit quis justo ac, pretium tempor turpis. Curabitur scelerisque interdum mauris et ornare. Donec et tristique magna. Duis bibendum fermentum bibendum. Maecenas sed posuere enim.","position":3},{"type":"multiChoice","form":{"privacy":"public","required":false,"question":"Multipla","description":"","options":[{"value":"Option 1","id":0},{"value":"Opção 2","id":1},{"value":"Opção 3","id":2}]},"id":5,"reply":"1","position":5},{"type":"checkboxes","form":{"privacy":"public","required":false,"question":"Seleção","description":"","answersAllowed":"unlimited","exact":null,"rangeMin":null,"rangeMax":null,"options":[{"value":"Option 1","id":0},{"value":"Opção 2","id":1},{"value":"Opção 3","id":2}]},"id":7,"reply":[1,2],"reply-0":0,"reply-1":true,"reply-2":true,"position":7},{"type":"fileUploader","form":{"privacy":"public","required":false,"question":"Upload","description":""},"id":9,"reply":[{"project_id":null,"user_id":9,"name":"Googlepdf.pdf","description":null,"file":"https://esolidar-proto-uploads.s3.eu-west-1.amazonaws.com/whitelabel/5/projects/files/Googlepdf-30e42da8-41fd-488b-a5d7-3cccfb143d4b.pdf?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA25334ATHGOYXBR5J%2F20220603%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20220603T161113Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Signature=be756ffc6af03e8f33f2a4bd0f8aa16a89744c3201dca44f24aeef169ddd1173","file_type":"pdf","file_size":59492,"public":true,"is_form_file":true,"updated_at":"2022-06-03 16:11:13","created_at":"2022-06-03 16:11:13","id":593},{"project_id":null,"user_id":9,"name":"esolidar _ Ajudando a ajudar!.pdf","description":null,"file":"https://esolidar-proto-uploads.s3.eu-west-1.amazonaws.com/whitelabel/5/projects/files/esolidar_Ajudandoaajudar%21-9d82cd94-ef87-4f34-b982-14ef7ea158f4.pdf?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA25334ATHGOYXBR5J%2F20220603%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20220603T161131Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Signature=0a12865c20e2710c21177de6aee76bf593378d1a96bc1add9cd17be26daa9f06","file_type":"pdf","file_size":635746,"public":true,"is_form_file":true,"updated_at":"2022-06-03 16:11:31","created_at":"2022-06-03 16:11:31","id":594}],"position":9}]',
  draft: '{}',
  status: 'APPROVED',
  uuid: '9ee595dc-93ae-4dcb-8e1c-64cf78f0d806',
  status_reason:
    '[{"user_id":9,"status":"APPROVED","reason":"teste","created_at":"2022-06-07T08:51:16.998Z"},{"user_id":9,"status":"REJECTED","reason":"asdasd","created_at":"2022-06-07T08:51:44.299Z"},{"user_id":9,"status":"APPROVED","reason":"zxcssafsd","created_at":"2022-06-07T08:51:59.432Z"},{"user_id":9,"status":"APPROVED","reason":"aaa","created_at":"2022-06-07T10:35:21.911Z"}]',
  updated_at: '2022-06-06 14:15:58',
  created_at: '2022-06-03 16:11:53',
  followers_count: 3,
  following: false,
  review_average: 4,
  whitelabel_config: {
    id: 5,
    company_id: 1,
    domain: null,
    subdomain: 'whitelabel.esolidar.local',
    company: {
      id: 1,
      name: 'Webankor (eSolidar)',
      logo: 'https://esolidar-proto-uploads.s3.eu-west-1.amazonaws.com/companies/313f4af4-4627-4885-b044-84e967ba9c73.jpeg',
      cover_image:
        'https://cdn.testesolidar.com/companies/1/cover/3f91a5b1-8620-4cd5-aec7-f76a05454bf7.jpg',
      thumbs: {
        detail:
          'https://cdn.testesolidar.com/companies/313f4af4-4627-4885-b044-84e967ba9c73-DETAIL.jpeg',
        thumb:
          'https://cdn.testesolidar.com/companies/313f4af4-4627-4885-b044-84e967ba9c73-THUMB.jpeg',
        cover_image:
          'https://cdn.testesolidar.com/companies/1/cover/3f91a5b1-8620-4cd5-aec7-f76a05454bf7.jpg',
      },
      s3_logo_key: 'companies/313f4af4-4627-4885-b044-84e967ba9c73.jpeg',
      s3_cover_key: 'companies/1/cover/3f91a5b1-8620-4cd5-aec7-f76a05454bf7.jpg',
      country: null,
      currency: null,
    },
  },
  ods: [ods],
  user,
  project_category: null,
  project_categories: [
    {
      id: 463,
      whitelabel_id: 5,
      project_config_id: 463,
      name: 'Água',
      summary:
        'Soluções que tentam minimizar o uso de água e novos métodos para reciclar ou reutilizar água',
      status: 1,
      image: 'projects/categories/water.jpg',
      updated_at: '2022-06-03 16:04:41',
      created_at: '2022-06-03 16:04:41',
      pivot: {
        project_id: 370,
        project_category_id: 463,
      },
    },
  ],
  images: [
    {
      id: 761,
      project_id: 370,
      streamImage: 'amazons3',
      image: 'whitelabel/5/projects/df3a64cb-0e1c-439b-b677-d79efd5be8e7.jpg',
      image_type: 'jpg',
      image_size: 92523,
      default: 1,
      position: 1,
      updated_at: '2022-06-03 16:11:53',
      created_at: '2022-06-03 16:08:46',
    },
    {
      id: 762,
      project_id: 370,
      streamImage: 'amazons3',
      image: 'whitelabel/5/projects/3c293b34-a894-4047-b12b-3b4c844fc20f.jpg',
      image_type: 'jpg',
      image_size: 334346,
      default: 0,
      position: 3,
      updated_at: '2022-06-03 16:11:53',
      created_at: '2022-06-03 16:09:00',
    },
    {
      id: 763,
      project_id: 370,
      streamImage: 'amazons3',
      image: 'whitelabel/5/projects/e48a87e8-2218-49ab-9e21-b2e731579e09.jpg',
      image_type: 'jpg',
      image_size: 29498,
      default: 0,
      position: 2,
      updated_at: '2022-06-03 16:11:53',
      created_at: '2022-06-03 16:09:37',
    },
  ],
  auctions: [
    {
      id: 423,
      user_id: null,
      cause_id: null,
      project_id: 370,
      sub_category_id: null,
      currency_id: 1,
      title: 'Leilão 1',
      title_en: null,
      position: 1,
      description: 'Leilão 1',
      description_en: null,
      shipping_description: '',
      shipping_description_en: null,
      payment_description: '',
      payment_description_en: null,
      tags: null,
      bid_start: 5,
      buy_now: 0,
      goal: null,
      video: null,
      dateStart: '2021-05-30 02:00:00',
      dateLimit: '2021-06-05 02:00:00',
      timezone: 'Europe/Lisbon',
      bid_interval: 1,
      bid_max_interval: 100,
      tax: 0,
      acquisition_value: 0,
      status: 'A',
      show_on_esolidar: '',
      private: 0,
      user_winner_notified: 0,
      rockinrio: 0,
      cc: 0,
      brand_id: 157,
      celebrity_id: null,
      updatedDate: '2022-06-07 08:14:44',
      dateAdded: '2021-05-30 18:53:29',
      last_bid: null,
      bids_count: 0,
      images: [
        {
          id: 684,
          auction_id: 423,
          streamImage: 'amazons3',
          image_name:
            'https://esolidar-proto-uploads.s3.eu-west-1.amazonaws.com/products/bbbffc4f-8f9f-4044-ba9e-ae0ec7f16069.jpeg',
          image_type: 'image/jpeg',
          image_size: '532764',
          default: 0,
          thumb: 0,
          position: 1,
          fb_image: 0,
          lastUpdated: '2021-05-30 18:53:29',
          dateAdded: '2021-05-30 18:47:35',
          thumbs: {
            standard:
              'https://cdn.testesolidar.com/products/bbbffc4f-8f9f-4044-ba9e-ae0ec7f16069-STANDARD.jpeg',
            detail:
              'https://cdn.testesolidar.com/products/bbbffc4f-8f9f-4044-ba9e-ae0ec7f16069-DETAIL.jpeg',
            pin: 'https://cdn.testesolidar.com/products/bbbffc4f-8f9f-4044-ba9e-ae0ec7f16069-PIN.jpeg',
            thumb:
              'https://cdn.testesolidar.com/products/bbbffc4f-8f9f-4044-ba9e-ae0ec7f16069-THUMB.jpeg',
          },
          s3_key: 'products/bbbffc4f-8f9f-4044-ba9e-ae0ec7f16069.jpeg',
        },
      ],
      currency: {
        id: 1,
        name: 'Euro',
        small: 'EUR',
        value: '1.071',
        symbol: '€',
        status: true,
        lastUpdate: '2022-06-09 01:00:15',
      },
    },
  ],
  crowdfundings: [
    {
      id: 135,
      user_id: 9,
      institution_id: null,
      company_id: 1,
      sub_category_id: null,
      product_id: 205,
      title: 'Campanha do projeto',
      title_en: null,
      tags: null,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer felis mauris, rutrum eget bibendum quis, volutpat vitae mi. Aenean turpis diam, facilisis vel ex at, ultrices commodo metus. Vestibulum tempus non nisi in mollis. Vivamus posuere eleifend eros, at pulvinar magna dignissim non. Nulla facilisi. Quisque porta malesuada enim, id sodales lacus vehicula a. Suspendisse a dolor dapibus dolor rutrum elementum eu at arcu. Etiam turpis sem, viverra vitae dolor vel, lacinia dignissim mi. Duis et sapien id diam accumsan venenatis a porttitor ligula. Duis tincidunt justo nec pharetra vestibulum. Proin facilisis nisi neque, convallis sollicitudin sapien hendrerit egestas. Nunc dictum, urna sit amet rutrum tincidunt, libero augue condimentum enim, id cursus ligula lectus sit amet lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam luctus elit a risus sagittis feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n\nSed blandit et ex a vulputate. Maecenas ullamcorper cursus risus, sit amet consequat mauris fermentum non. Morbi vel maximus ex. Vivamus interdum diam ex, ac luctus ante consequat vitae. Nam fringilla enim sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla tempus velit nulla, quis fermentum justo fermentum et.\n\nDonec porttitor porta neque, sit amet dapibus turpis. Mauris viverra velit ac sollicitudin auctor. Morbi sed rutrum ante, et accumsan augue. In luctus justo nec erat fermentum tincidunt. Sed iaculis metus vitae sagittis bibendum. Proin laoreet, libero eget tempus vehicula, est justo facilisis velit, vitae dignissim massa metus id risus. Vestibulum tincidunt massa justo, at condimentum felis pulvinar vitae. Quisque tincidunt semper ex, at faucibus risus varius tristique. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla auctor malesuada iaculis. Aliquam aliquam ex quis velit pellentesque tempus.',
      description_en: null,
      video: null,
      reward: 1,
      reward_description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer felis mauris, rutrum eget bibendum quis, volutpat vitae mi. Aenean turpis diam, facilisis vel ex at, ultrices commodo metus. Vestibulum tempus non nisi in mollis. Vivamus posuere eleifend eros, at pulvinar magna dignissim non. Nulla facilisi. Quisque porta malesuada enim, id sodales lacus vehicula a. Suspendisse a dolor dapibus dolor rutrum elementum eu at arcu. Etiam turpis sem, viverra vitae dolor vel, lacinia dignissim mi. Duis et sapien id diam accumsan venenatis a porttitor ligula. Duis tincidunt justo nec pharetra vestibulum. Proin facilisis nisi neque, convallis sollicitudin sapien hendrerit egestas. Nunc dictum, urna sit amet rutrum tincidunt, libero augue condimentum enim, id cursus ligula lectus sit amet lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam luctus elit a risus sagittis feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n\nSed blandit et ex a vulputate. Maecenas ullamcorper cursus risus, sit amet consequat mauris fermentum non. Morbi vel maximus ex. Vivamus interdum diam ex, ac luctus ante consequat vitae. Nam fringilla enim sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla tempus velit nulla, quis fermentum justo fermentum et.\n\nDonec porttitor porta neque, sit amet dapibus turpis. Mauris viverra velit ac sollicitudin auctor. Morbi sed rutrum ante, et accumsan augue. In luctus justo nec erat fermentum tincidunt. Sed iaculis metus vitae sagittis bibendum. Proin laoreet, libero eget tempus vehicula, est justo facilisis velit, vitae dignissim massa metus id risus. Vestibulum tincidunt massa justo, at condimentum felis pulvinar vitae. Quisque tincidunt semper ex, at faucibus risus varius tristique. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla auctor malesuada iaculis. Aliquam aliquam ex quis velit pellentesque tempus.',
      goal: 5000,
      minimum_contribution: 10,
      currency_id: 1,
      start_date: '2022-06-05 23:00:00',
      end_date: '2022-06-29 23:00:00',
      timezone: 'Europe/Lisbon',
      position: 0,
      recipient_visible: 1,
      status: 'approved',
      esolidar_list: 0,
      updated_at: '2022-06-06 15:09:55',
      created_at: '2022-06-06 15:07:59',
      contributes_sum: 0,
      laravel_through_key: 370,
      images: [
        {
          id: 485,
          crowdfunding_id: 135,
          streamImage: 'amazons3',
          image: 'crowdfundings/sample-abf4575a-e503-49d2-8b3b-0bca5b896dbe.jpg',
          image_type: 'jpg',
          image_size: 26196,
          default: 0,
          position: 1,
          updated_at: '2022-06-06 15:07:59',
          created_at: '2022-06-06 15:07:42',
        },
      ],
      currency: {
        id: 1,
        name: 'Euro',
        small: 'EUR',
        value: '1.071',
        symbol: '€',
        status: true,
        lastUpdate: '2022-06-09 01:00:15',
      },
    },
  ],
};

export default projectOverview;
