const setPassword404 = {
  request_time: 11,
  code: 404,
  data: {
    message: 'No query results for model [App\\Models\\UserRecoveryPasswordCodes].',
    exception: 'Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException',
    file: '/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php',
    line: 385,
    trace: [
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php',
        line: 332,
        function: 'prepareException',
        class: 'Illuminate\\Foundation\\Exceptions\\Handler',
        type: '->',
      },
      {
        file: '/var/www/app/Exceptions/Handler.php',
        line: 73,
        function: 'render',
        class: 'Illuminate\\Foundation\\Exceptions\\Handler',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php',
        line: 51,
        function: 'render',
        class: 'App\\Exceptions\\Handler',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 130,
        function: 'handleException',
        class: 'Illuminate\\Routing\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/app/Http/Middleware/Filters/SentryContextFilter.php',
        line: 41,
        function: 'Illuminate\\Pipeline\\{closure}',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 167,
        function: 'handle',
        class: 'App\\Http\\Middleware\\Filters\\SentryContextFilter',
        type: '->',
      },
      {
        file: '/var/www/app/Http/Middleware/Filters/StartApiFilter.php',
        line: 35,
        function: 'Illuminate\\Pipeline\\{closure}',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 167,
        function: 'handle',
        class: 'App\\Http\\Middleware\\Filters\\StartApiFilter',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 103,
        function: 'Illuminate\\Pipeline\\{closure}',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php',
        line: 697,
        function: 'then',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php',
        line: 672,
        function: 'runRouteWithinStack',
        class: 'Illuminate\\Routing\\Router',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php',
        line: 636,
        function: 'runRoute',
        class: 'Illuminate\\Routing\\Router',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php',
        line: 625,
        function: 'dispatchToRoute',
        class: 'Illuminate\\Routing\\Router',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php',
        line: 166,
        function: 'dispatch',
        class: 'Illuminate\\Routing\\Router',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 128,
        function: 'Illuminate\\Foundation\\Http\\{closure}',
        class: 'Illuminate\\Foundation\\Http\\Kernel',
        type: '->',
      },
      {
        file: '/var/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php',
        line: 67,
        function: 'Illuminate\\Pipeline\\{closure}',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 167,
        function: 'handle',
        class: 'Barryvdh\\Debugbar\\Middleware\\InjectDebugbar',
        type: '->',
      },
      {
        file: '/var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php',
        line: 58,
        function: 'Illuminate\\Pipeline\\{closure}',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 167,
        function: 'handle',
        class: 'Fruitcake\\Cors\\HandleCors',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php',
        line: 86,
        function: 'Illuminate\\Pipeline\\{closure}',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 167,
        function: 'handle',
        class: 'Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php',
        line: 103,
        function: 'Illuminate\\Pipeline\\{closure}',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php',
        line: 141,
        function: 'then',
        class: 'Illuminate\\Pipeline\\Pipeline',
        type: '->',
      },
      {
        file: '/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php',
        line: 110,
        function: 'sendRequestThroughRouter',
        class: 'Illuminate\\Foundation\\Http\\Kernel',
        type: '->',
      },
      {
        file: '/var/www/public/index.php',
        line: 54,
        function: 'handle',
        class: 'Illuminate\\Foundation\\Http\\Kernel',
        type: '->',
      },
    ],
  },
};

export default setPassword404;
