name: Run

on: [pull_request]

jobs:
  install:
    name: install app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com
          scope: '@esolidar'

      - name: Install dependencies
        run: yarn --pure-lockfile --production=false
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  lint:
    name: Run code lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn test:lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npx jest --colors

  coverage:
    name: Coverage tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Run tests
        run: yarn jest --json --outputFile="/home/runner/work/_actions/mattallty/jest-github-action/v1/dist/jest.results.json"
      - name: Add Coverage Comment
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo done'

  allPass:
    name: Well done
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - run: exit 0
