name: publish-pr-branch

on: [pull_request]

jobs:
  install:
    name: install app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com
          scope: '@esolidar'

      - name: Install dependencies
        run: yarn --pure-lockfile --production=false
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/pulls/{pull}
          repository: ${{ github.repository }}
          pull: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/deployments
          repository: ${{ github.repository }}
          ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
          environment: dev
          auto_merge: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  allPass:
    name: Well done
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - run: exit 0
