name: publish-github-package

on:
  push:
    branches: ['master']

jobs:
  publish:
    runs-on: ubuntu-latest
    name: publish-package
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com
          scope: '@esolidar'

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish package
        run: yarn build:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: lib
